name: imageSeg
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.1=cpu_0
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - async_generator=1.10=py37h28b3542_0
  - attrs=20.2.0=py_0
  - backcall=0.2.0=py_0
  - beautifulsoup4=4.9.3=pyhb0f4dca_0
  - blas=1.0=mkl
  - bleach=3.2.1=py_0
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.5=py37_0
  - conda-build=3.18.11=py37_0
  - conda-package-handling=1.6.1=py37h7b6447c_0
  - cpuonly=1.0=0
  - cryptography=3.1.1=py37h1ba5d50_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - cycler=0.10.0=py37_0
  - dbus=1.13.16=hb2f20db_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_0
  - expat=2.2.9=he6710b0_2
  - filelock=3.0.12=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.2=h5ab3b9f_0
  - glib=2.65.0=h3eb4bd4_0
  - glob2=0.7=py_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - icu=58.2=he6710b0_3
  - idna=2.10=py_0
  - importlib-metadata=1.7.0=py37_0
  - importlib_metadata=1.7.0=0
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.16.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py37_0
  - jedi=0.17.2=py37_0
  - jinja2=2.11.2=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=py_0
  - jsonschema=3.2.0=py37_1
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37_0
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_server=1.2.0=py_0
  - kiwisolver=1.2.0=py37hfd86e86_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libarchive=3.4.2=h62408e4_0
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblief=0.10.1=he6710b0_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.3.1=0
  - matplotlib-base=3.3.1=py37h817c723_0
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclient=0.5.0=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.0.7=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - notebook=6.1.4=py37_0
  - numpy=1.18.5=py37ha1c710e_0
  - numpy-base=1.18.5=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h7b6447c_0
  - packaging=20.4=py_0
  - pandoc=2.10.1=0
  - pandocfilters=1.4.2=py37_1
  - parso=0.7.0=py_0
  - patchelf=0.11=he6710b0_0
  - pcre=8.44=he6710b0_0
  - pexpect=4.8.0=py37_1
  - pickleshare=0.7.5=py37_1001
  - pillow=7.2.0=py37hb39fc2d_0
  - pip=20.2.3=py37_0
  - pkginfo=1.5.0.1=py37_0
  - prometheus_client=0.8.0=py_0
  - prompt-toolkit=3.0.7=py_0
  - psutil=5.7.2=py37h7b6447c_0
  - ptyprocess=0.6.0=py37_0
  - py-lief=0.10.1=py37h403a769_0
  - pycosat=0.6.3=py37h7b6447c_0
  - pycparser=2.20=py_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - pysocks=1.7.1=py37_1
  - python=3.7.7=hcff3b4d_5
  - python-dateutil=2.8.1=py_0
  - python-libarchive-c=2.9=py_0
  - pytorch=1.3.1=cpu_py37h62f834f_0
  - pytorch-cpu=1.1.0=py3.7_cpu_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py37h7b6447c_0
  - pyzmq=19.0.2=py37he6710b0_1
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=py_0
  - ripgrep=12.1.1=0
  - ruamel_yaml=0.15.87=py37h7b6447c_0
  - send2trash=1.5.0=py37_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - sip=4.19.8=py37hf484d3e_0
  - six=1.15.0=py_0
  - soupsieve=2.0.1=py_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.4.2=cpu_py37h9ec355b_0
  - tornado=6.0.4=py37h7b6447c_1
  - tqdm=4.50.2=py_0
  - traitlets=5.0.4=py_0
  - unzip=6.0=h611a1e1_0
  - urllib3=1.25.10=py_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.2=he6710b0_3
  - zip=3.0=h1adfe0e_0
  - zipp=3.3.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - style==1.1.0
    - update==0.0.1
prefix: /opt/conda
